### ISSUE TITLE
2k11's user.css is loaded if selected theme does not have user.css

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#349] opened 2015-06-17 17:17 UTC
*  Add user.css to 2k11.
   *  Use theme OTHER than 2k11.
   *  If other theme does not have its own user.css, it will be loaded from 2k11.

**Comment by yellowled** [comment] 2015-06-17 20:12
It is reproducable in `master`. So is the expected behaviour “if a theme dir does not contain a user.css, do not include the user.css in serendipity.css.php”? If so, we're probably looking at

```
$out .= serendipity_printStylesheet(
         serendipity_getTemplateFile($css_userfile, 'serendipityPath', true),
         serendipity_getTemplateFile($css_userfile, '', true)
);
```
and we'd probably have to check if `$userfile` (which is `user.css`) exists in the current themes directory.

**Comment by donchambers** [comment] 2015-06-17 20:49
> So is the expected behaviour “if a theme dir does not contain a user.css, do not include the user.css in serendipity.css.php”?

Yes - that is how I would expect it to behave.  Use only the active theme's user.css if it exists.

**Comment by garvinhicking** [comment] 2015-06-18 08:59
Hm, this is harder than it seems. When a theme uses the 2k11 engine and only provides some minor details, it might be nice that the user.css of 2k11 is loaded (which the user created himself).

We could tell users to put a empty user.css file into the custom theme directory to prevent this; one might even consider it a feature that a user.css file which has been created applies to every theme, so that someone only has to make this change once (i.e. larger font size) and it applies to every theme....?!

**Comment by yellowled** [comment] 2015-06-18 09:19
I have never really build a theme using an engine theme, but if you look at the Photo theme which uses 2k11 as its engine, I *highly* doubt that anyone would want to user a `user.css` that was created for 2k11 with that.

After all, the whole concept of engine themes is more about `.tpl` file inheritance than it is about CSS, isn't it? Any child theme will have its own `style.css`, so why should a `user.css` that was written for a *different* `style.css` work well with that?

**Comment by garvinhicking** [comment] 2015-06-18 09:26
I have not worked with user.css's on my own, but I would use it to change colors and font sizes and maybe widths, so only minor tweaks to a file. And since .tpls are shared, CSS classes would be shared and could be applied, too....?!

**Comment by ophian** [comment] 2015-06-18 09:43
It is only a problem if a user has put a user.css to the 2k11 standard template and then changes the user theme. It is his own responsibility to disable or remove it, or prevent its load by an empty user.ccs file, when using another theme. I think we can announce this clearly. 
Its a little more difficult with templatechooser though.

**Comment by yellowled** [comment] 2015-06-18 09:52
> I would use it to change colors and font sizes and maybe widths, so only minor tweaks to a file.

That may very well be true, but I have also seen people use it to make much larger tweaks, simply because it is update-safe and easier (for some users) than to fork. Also, people seem to be afraid to miss updates if they fork.

Still, the child theme using 2k11 as an engine theme may deviate very much from 2k11. Have [a look at Photo](https://onli.columba.uberspace.de/s9y/). Doesn't look like 2k11, does it? :)

**Comment by yellowled** [comment] 2015-06-18 09:53
That being said, I think the solution to put an empty `user.css` in the new theme's directory is perfectly fine. I don't see any disadvantages to that, either.

**Comment by donchambers** [comment] 2015-06-18 13:08
> Hm, this is harder than it seems. When a theme uses the 2k11 engine and only provides some minor details, it might be nice that the user.css of 2k11 is loaded (which the user created himself).

Maybe - but the scenario I referred to for this issue is not a 2k11 child theme.

> We could tell users to put a empty user.css file into the custom theme directory to prevent this; one might even consider it a feature that a user.css file which has been created applies to every theme, so that someone only has to make this change once (i.e. larger font size) and it applies to every theme....?!

Only a user.css created within the 2k11 folder will apply to every theme that does not have its own user.css.

May I ask why this is difficult to implement?  I personally think users shouldn't have to play games to prevent a theme other than 2k11 from being styled by 2k11's user.css if it exists.  There is also the issue, @ophian pointed out regarding templatechooser plugin.  I will add another to that: properties/templates of categories (serendipity_event_categorytemplates).

**Comment by garvinhicking** [comment] 2015-06-18 13:18
@donchambers The reason is not necessarily technical, it's also conceptual. 2k11 is as much core as "default" is, and thus part of the fallback chain.

So, conceptually it's the place where you would place files that should apply across themes.

And technically, if we were to change it, we'd need to make a specific exemption for a file called "user.css" (or add a new parameter to serendipity_getTemplateFile() which is already a bit too heavyweight nowaday) to not go through the fallback route. That could lead to errors much more serious than the current usage of the file.

Personally, I am in favor of keeping it the current way, because while there is a way to prevent a user.css in a template directory (with an empty file), if we patched away this thing, there would be no way to have a globally used CSS file across every theme. A user would have to put a distinct user.css into each and every template directory, if he for example specifically styled a HTML nugget in a way that seems fit for him.

I'm open to discussion, if you other people think this is not good, I'll bow to patching it.

**Comment by onli** [comment] 2015-06-18 16:22
I think it is a bug and should be fixed - we already know that it confuses users, we don't display the integration properly, and I highly doubt that any user.css would apply to a typical theme using 2k11 as Engine (even if photo is an extreme example of that, given the scope of the changes - but yes, even Link colours would not work at all there).

I would change my opinion if we integrate the user.css properly into the backend, and show that it applies globally (in case it does, Engine and stuff).

**Comment by yellowled** [comment] 2015-06-18 16:35
On the one hand, I like to take these things pragmatically. That would be to propagate the “empty user.css” solution and be done with it.

> if we patched away this thing, there would be no way to have a globally used CSS file across every theme

Well, we could have an additional `global-user.css` … (Just kidding, obviously.) I really don't think a file like this is necesssary. The number of users that switch themes regularly isn't very high, but the number of people that want to apply the *same* changes to *any* theme they use should be next to zero.

> A user would have to put a distinct user.css into each and every template directory, if he for example specifically styled a HTML nugget in a way that seems fit for him.

Well, technically, he could have those styles inline in the HTML nugget (and I'm afraid some people would do that), but I think that's an edge case, and I think it is perfectly acceptable to have to copy styles from one `user.css` to another in those cases. I mean, how often do people switch themes anyway?

On the other hand, is it desirable to have (potentially) dozens of `user.css` in the `templates` directories?

**Comment by donchambers** [comment] 2015-06-18 16:37
> [...] there would be no way to have a globally used CSS file across every theme. A user would have to put a distinct user.css into each and every template directory, if he for example specifically styled a HTML nugget in a way that seems fit for him.

I maintain my position that user.css should be theme specific, and no theme, including 2k11, should affect the style of another theme - unless it is a parent/child theme.

I cannot imagine a scenario where css changes for one theme will always make sense across all other themes.  You could have id or class names in common quite by accident.  If, however, we wanted this, why don't we create something specifically for that purpose... such as serendipity-global.css which could reside in the default folder??

I became aware of this unintended inheritance due to an s9y user implementing my latest theme - that user didn't even realize my theme was being affected by his 2k11 user.css because he wasn't as intimately familiar with the theme as I am.  I am afraid the same could happen in the future if we don't change how automagically including user.css currently works.

**Comment by ophian** [comment] 2015-06-18 17:33
> and no theme, including 2k11, should affect the style of another theme - unless it is a parent/child theme.

But this Parent/Child relation exactly is the case wth it. 2k11 is the parent of all custom themes! And default is the parent of 2k11. That is what Garvin explained well.
Therefore the fallback behaves exactly as it should. 

When I place a user.css file to the standard (parent) template 2k11 intentionally, I must be aware that it is my responsibility to rename, delete, or overwrite it with my next chosen custom theme user.css file. Thats all to know and to learn. Its the same for any other file loaded by getTemplateFile().

This also applys well to templatechooser or categorytemplates usage.

It is not about having a global user.css, its about this parent/child relation as being the standard template.

**Comment by onli** [comment] 2015-06-18 17:46
> When I place a user.css file to the standard (parent) template 2k11 intentionally, I must be aware that it is my responsibility to rename, delete, or overwrite it with my next chosen custom theme user.css file. 

No. No user can be expected that photo is a child of 2k11, and every new theme will be a child of 2k11.

**Comment by garvinhicking** [comment] 2015-06-19 07:43
My "global user.css scenario" would apply to:

* specific HTML nuggets or plugin containers in the sidebar (most of s9y's themes share the same unique ID for nuggets, don't they?)
* specific CSS classes that I use in my blog entry's HTML (<div class="sponsormessage">)
* increase font size of all <p> tags in my blog

Especially blogs that run the templatechooser plugin can benefit from a global CSS that gets loaded everywhere, without tampering with EVERY SINGLE template directory. Please keep in mind that with the current solution we have a workaround, but if we "fixed" the issue, we would have no workaround to keep this scenario.

**Comment by onli** [comment] 2015-06-19 08:18
No modern theme will make it possible to increase the font size generically. Even if that is centralized in the css, the approach to change it properly changes with every theme.

Same goes for the concrete styling of a html nugget.

I think that it is a completely imaginary use case :)

**Comment by yellowled** [comment] 2015-06-19 08:22
Again, I'm not advocating 100% pro or con for either solution, just some thoughts.

> most of s9y's themes share the same unique ID for nuggets, don't they?

If you mean `id="..."`, no, because that's not even emitted. Usually, HTML nuggets get a `class="serendipity_plugin_html_nugget"`. I thought Bulletproof did emit a unique ID for every HTML nugget, but I seem to remember that wrong … although I know there is a way to emit a unique ID for nuggets, I just don't remember how right now.

> specific CSS classes that I use in my blog entry's HTML

In my humble opinion, that is kind of advanced. I'm not sure how many people actually use that. Again, this is not to advocate against it, I'm just trying to see this pragmatically.

> increase font size of all tags in my blog

That might or might not even work in user.css, depending on how the theme styles the font sizes of it's elements.

I see where you're coming from, @garvinhicking, but judging from my CSS experience, these are edge cases. For instance, setting the font sizes in a user.css to be applied to *any* theme you're ever going to use in your blog is just not necessary. I would assume that you always check the looks provided by the theme and *then* maybe adapt them if necessary. You should not assume that your old styles will work with a new theme as well. (Think about link colors as well, that may be the better example.)

Special classes for entries and nuggets, those I can see. But I still think that only a few users actually use that, and those can – in my opinion – be expected to carry over their styles to a new `user.css` in a different theme directory. They may even have to adapt them anyway because – as @donchambers pointed out – the new theme may not use the same markup, the same classes.

I agree with @onli that not every user (think about *new* users, for instance; or people that do not frequent the forums, but still use s9y) can be expected to know about the inner workings of the template fallback chain. Ideally, this should “just work” (for lack of a better term) without confusing users. On the other hand, adding a user.css and adding CSS to that is kind of advanced, so it's not necessarily new users we're talking about here.

**Comment by yellowled** [comment] 2015-06-19 08:24
> No modern theme will make it possible to increase the font size generically.

A truly modern theme will make it possible to just set the `font-size` for `html` or `body` and have all other font sizes adapt to that by using relative units for `font-size`.

But that's probably not what you meant. :-)

**Comment by onli** [comment] 2015-06-19 08:28
I meant a bit the html *or* body part ;)

**Comment by ophian** [comment] 2015-06-19 08:31
I don't understand this global user.css discussion. I never had the need to do such as being too unprecise and I use such file often. Users in real need to run multi templates, may put a user.css to 2k11 - which then acts like a global fallback to all themes running.

The Issue is about this load in standard template. This is the correct behaviour, since standard = parent fallback. Everythings works as expected. Why did this come up? Someone had used a tweaked standard template before and then switched his theme. He forgot to remove his tweak from fallback or carry it foreward. That is all about. So we may talk about how to avoid people forgetting this point of fallback.

Every action tweaking getTemplateFile is too much for this precision. Why did this come up at all? Since we moved the user.css to be autoloaded. I think this is OK on our way moving forward, particularly since we needed to include a "admin/user.css" file.

Imagine the theme is missing a tpl file. First search will be in 2k11 standard. This is the same behaviour and situation.

**Comment by yellowled** [comment] 2015-06-19 08:40
> So we may talk about how to avoid people forgetting this point of fallback.

The point is that *average users* can and should not be expected to know about this. They may have been told in the forums to add a user.css and to add CSS to that. They may even have been told *what* CSS to put there. There are a *lot* of people who want to make changes like these using the user.css that do not know how to write the most basic things in CSS. And while I would prefer that these people learn some CSS instead, I guess it's perfectly legitimate to want to customize your theme without knowing CSS these days.

I'm not saying it is “our duty” to make all this as simple as possible for them. Other systems don't even *have* something like a user.css, there you would have to adapt your theme, period. But since we agreed to make this possible in the first place, we should at least think about if this is usable for end users.

**Comment by ophian** [comment] 2015-06-19 08:52
> The point is that average users can and should not be expected to know about this.

I think they should learn about it! It is by design/concept. And it is not about the user.css file alone.
So we have a clear fallback and now try to get rid of it since being confusing? IMHO: No we should not and try our best to communicate this feature.

**Comment by yellowled** [comment] 2015-06-19 09:02
> I think they should learn about it!

Again, this is just a pragmatic way of thinking, I'm not saying I have the “right” opinion on this.

For instance, I think people should learn how to write at least the most basic CSS if they want to customize their own blog. Years and thousands of forum posts later, I still explain to people how to set the `font-size` of an `h3` in the sidebar on a regular basis.

I get where you're coming from, but saying that people should learn about this means assuming that they *want* to learn about this. This is actually a very fundamental point – what is more important, flexibility or ease of use? I'm not sure we can always have both …

**Comment by ophian** [comment] 2015-06-19 09:26
> what is more important, flexibility or ease of use? I'm not sure we can always have both …

We already have and want both! This is Serendipity as long as I know it! This doesn't touch the easy use part. It is still easy to put a user.css to a theme and it is clearly announced in the streamed css file.
```css
/* auto include templates/UserThemeName/user.css */
...
```
Abd the flexibility is the fallback.

**Comment by yellowled** [comment] 2015-06-19 09:29
> It is still easy to put a user.css to a theme and it is clearly announced in the streamed css file. […] And the flexibility is the fallback.

I'm not sure if that is the ease of use and flexibility of a (potentially new) end user or the ease of use and flexibility of a coder and an experienced user. I'm pretty sure many users are not even aware that there *is* a streamed CSS file or a fallback chain …

**Comment by donchambers** [comment] 2015-06-19 13:25
I understand the consequences of global css, regardless of how I personally believe it will have little or no practical benefit or usage on a real site.

We created user.css in bulletproof, to provide a voluntary, template-specific, update safe way for users to modify their site's behavior without ever modifying the theme's core stylesheet.  The idea was a big success, and several themes used this concept.

By automatically including user.css (if it exists), we have run into an unintended consequence due to the fallback chain.  Now, users MUST create a user stylesheet to PREVENT a different theme from impacting their own.  In its worse case scenario, a user that wants 2k11, complete with its user.css modifications to exist, but also wants the option of using multiple additional themes.

I would never expect a different theme's core stylesheet to affect my theme's styles. I think the same should be true of a user created stylesheets.  2k11's style.css has no effect on my theme... 2k11's user.css shouldn't either...  unless this screws up the whole engine concept.

If this current fallback methodology for user.css does not change, how about a big warning somewhere in the theme selection page that a 2k11 user.css exists (when it does) and will impact the appearance of any selected theme unless renamed, deleted, or theme-specific user.css is created??

**Comment by garvinhicking** [comment] 2015-06-19 13:39
@donchambers But that's actually the point, it's NOT a theme's core stylesheet. User.css is something that I intentionally created, and it is not part of the theme itself, but my specific variant of it. So actually I would understand if that file would be used on other themes as well.

I do think your suggestion of a info on the theme selection page could be a good place, for people who don't look into the CSS generated source. A message like: 

```
"You have created a user.css file in the 2k11 directory, which is used as the default 'fallback chain' directory for any files that other themes do not contain. This file will also be used by any other theme which does not provide it's own  user.css file. You can individually prevent this by placing an empty user.css file in each template directory where that file should not be used.".
```

This is a bit verbose, but also tries to explain the "fallback chain" thingie.

@onli Would you have a proposal on how to actually patch the user.css fallback so that it works like you and Don would propose? If so, we could simply issue a vote, and the way I see it @yellowled would be the tipping point (@onli and @donchambers are in favor of changing, @garvinhicking and @ophian in favor of keeping) ;-)

**Comment by yellowled** [comment] 2015-06-19 14:21
If you guys seriously think that *I* – who tried to see *both* sides throughout the whole discussion – am going to play the one to tip the scales here, you are so wrong, it's not even funny. ;-)

**Comment by yellowled** [comment] 2015-06-19 14:26
> A message like […]

Where and how would that be emitted, though? Show it if a `user.css` exists in `templates/2k11/` and show it on top of the theme list in the backend? Show it all the time (very annoying) or show it only until someone confirms to have read it by clicking „Okay“? What about multi-user blogs? Does every editor in a multi-user blog have to be informed about some CSS change that the admin user made? (I don't think so.)

**Comment by yellowled** [comment] 2015-06-19 14:28
> User.css is something that I intentionally created, and it is not part of the theme itself, but my specific variant of it. So actually I would understand if that file would be used on other themes as well.

The first statement: yes. The second statement: not so much. While I may understand that I created said file, how am I supposed to know that it is part of the fallback chain, especially (and this is kind of the point) since that was *not* the case before?

**Comment by ophian** [comment] 2015-06-19 14:33
> especially (and this is kind of the point) since that was not the case before?

easy to solve by writing a nice upgrade notice to 2.0.2!

**Comment by donchambers** [comment] 2015-06-19 14:43
> Show it if a user.css exists in templates/2k11/ and show it on top of the theme list in the backend? Show it all the time (very annoying) 

Yes - either above the list of all themes, or within the box of the currently used theme.  I don't see it as overly annoying...  I see it as informative.  People are only on that page because they want to change themes, or change configuration items of a specific theme.

A possibility:  Show notice only if 2k11 has user.css, selected theme is not 2k11, and selected theme does not have user.css.  I still don't like how it works, but one or more notices/warnings would help educate users on how it works.

Now, having said this...  should we consider reversing the auto inclusion of user.css, and return to making it a template option?

**Comment by onli** [comment] 2015-06-19 16:19
We have three sound options:

 1. Show the content of the user.css in the backend, thus notifying the user in the theme settings, and otherwise keep it like it is (making the system transparent)
 2. Revert to the prior behaviour, one user.css per theme (minimizing the unexpected behaviour)
 3. Change the concept from an user.css to a global user.css, that lies under / or /templates, and always applies to all themes regardless (minimizing the unexpected behaviour)

We already know the behaviour is uexpected and we have no user input for the global theme user.css, so I would prefer 2. But can accept the other 2.

**Comment by yellowled** [comment] 2015-06-19 16:27
> We have three sound options

If those actually *are* the three options, I'd prefer 2. as well. But only because I feel 1. and 3. would be worse. Fine with Garvin picking, though.

**Comment by ophian** [comment] 2015-06-19 17:01
**4**. leave it as is, and announce this as a change to give attention to on upgrade. (Vote!)

**Comment by garvinhicking** [comment] 2015-06-22 07:44
Actually solution #2 would not really be "reverting". Because prior to that a user.css was a bulletproof-only feature and did not come from the core at all. This is why we'd need a patch to serendipity_getTemplateFile to add a specific exemption or new parameter to prevent the fallbackchain for a "user.css" file (which I'm struggling to do simply because it makes the function bloated and we didn't implement the last change discussed in https://github.com/s9y/Serendipity/issues/343

**Closed** 2015-09-02 15:55 UTC
Labels: 2.0, bugs, templates
