### ISSUE TITLE
Smarty include relative path with 2.0.1 behaviour changed

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#331] opened 2015-03-19 09:44 UTC
to need strict `./` in themes.
http://board.s9y.org/viewtopic.php?f=5&t=20321 and https://github.com/s9y/additional_themes/commit/7c2d9956de69fd768e273f44ad7a8ed4289d88d6
Old `{include file="example.tpl"}` fails, new `{include file="./example.tpl"}` works.

What might have changed (when), which could influence this behaviour in Smarty? 

It must be something regarding the template fetch "scope", like the stricter set of `serendipity_getTemplateFile()` for backend chainings we have touched. (i actually can`t see why this could influence it though)

Any ideas?

**Comment by garvinhicking** [comment] 2015-03-19 09:53
Don't know, I think this should be smarty related and not something in s9y itself... {include} is a fully internal smarty command, there's no s9y logic in there...?!

**Comment by ophian** [comment] 2015-03-19 10:11
I know, but it could be influenced, if the template scope path is not strict and maybe is an array in wrong order or something...

**Comment by garvinhicking** [comment] 2015-03-19 10:37
Hm. Maybe you could ask in the smarty forums on either if they know of an intentional change to this, or they can help debugging/where to look?

**Comment by ophian** [comment] 2015-03-19 11:00
I am pretty sure this would have had come up in the smarty forum, since 3.1.21 is "pretty" old. As I said already, I can't remember to have read something related in the smarty forum the last months. When we really do not know where to search for, I will certainly ask for it.
If you know where this is reproducible, enabling debugging at https://github.com/s9y/Serendipity/blob/master/include/functions_smarty.inc.php#L946 ff could help. I once did test this regarding a question by YL with an own include "something" (in 2k11 I think) and could not reproduce this behaviour.

**Comment by yellowled** [comment] 2015-03-19 11:10
>  could not reproduce this behaviour

That is actually the irritating factor in this. We have had two or three occurrences of this reported as far as I remember, and we have never been able to reproduce it. Smells like some (template) cache thing to me, since I think it always occurred in updated blogs and was tried to reproduce in test environments that were already set up using 2.0.

**Comment by ophian** [comment] 2015-03-19 11:27
Yeah, right! Maybe it has to do with the compiled template cleanup on upgrade, which was increased also... (so this would not happen with more current checkouts...?)

**Comment by garvinhicking** [comment] 2015-03-19 12:28
It was reproducible on blog.s9y.org which uses a 2.0.1 github checkout. It occured with completely fresh templates that were never used before.

It is also easily reproducible on any of my installations. Simply edit i.e. index.tpl of 2k11, add a:

```
{include file="test.tpl"}
````

and then create test.tpl with dummy content.

It  will create a fatal PHP error:

```
Fatal error: Uncaught --> Smarty: Unable to load template file 'test.tpl' in '/www/cvs/serendipity/recent/templates/2k11/index.tpl' <-- thrown in /home/garvin/cvs/serendipity/git/2.0/Serendipity/bundled-libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 129
```

I am using symlinks for my installation (blog.s9y.org does as well). Maybe that's an issue, but I don't know if @donchambers has the same setup. I currently have no access to any install that doesn't use symlinks, so I can't test this with a non-symlinked install right now.

Maybe Smarty checks the "realdir" of a file, and gets confused if that path is not in the template list (where the symlinked, not realdir, is configured). In my oppinion that would be a bug with Smarty; maybe it can be circumvented with a smarty option like "use symlinks" or whatever)

**Comment by donchambers** [comment] 2015-03-19 13:09
I'm not using symlinks, and as @garvinhicking  mentioned, he can easily reproduce the problem on any of his installations.  Did we change smarty versions between s9y 1.7.8 and 2.x?  Because this problem does NOT exist in 1.7.8.

**Comment by ophian** [comment] 2015-03-19 14:09
I am sorry, I cannot reproduce this! In my local setup with a current Serendipity v.2.0.1 in index.tpl
```
{include "mytest.tpl"}[1]
{include file="mytest.tpl"}[2]
```
mytest.tpl with `<h2>mytest.tpl</h2>`

Both works in templates/next/index.tpl.
Of course you get an error, if you have misspelled the include file.

**Comment by ophian** [comment] 2015-03-19 14:11
The realdir path thing may be a valid issue though.

**Comment by ophian** [comment] 2015-03-19 14:58
I think it must be the not correctly purged compiles thing, maybe having changed path to relpath with Smarty 3.1.21 update, for Don, YL and liebeszeit and the realdir path thing for symlinked directories users like Garvin.
I for myself cannot reproduce this in any tpl file of a template though.
It would be interesting for the three mentioned, when they had changed the errored include to use `./` instead to get out of this exception, what would happen if they just revert their changes, since they now are on current 2.0.x versions. ?!?

**Comment by yellowled** [comment] 2015-03-19 15:01
> when they had changed the errored include to use ./ instead to get out of this exception

I did not do that, I just added the contents of the included file (Piwik snippet) to my index.tpl.

**Comment by donchambers** [comment] 2015-03-19 16:15
> maybe having changed path to relpath with Smarty 3.1.21 update, for Don, YL and liebeszeit 

What exactly do you mean by that?


Here is what I did....

* Site running 1.7.8.
* Upgraded to 2.0.1.
 * did NOT purge templates_c
 * observed file not found error
 * modified to {include file="./filename.tpl"}
 * this modification corrected file not found error
* reverted to 1.7.8
 * did NOT purge templates_c
 * noted that modification of "./"filename.tpl also works in 1.7.8 (as it should - "./" is the current dir)
 * reverted to {include ="filename.tpl"}
 * observed that it continues to work in 1.7.8
 * re-upgraded to 2.0.1
 * file not found error returned
* re-upgraded to 2.0.1.
 * did NOT purge templates_c
 * again observed file not found error
 * again modified to {include file="./filename.tpl"}
 * again - this modification corrected file not found error

**Comment by ophian** [comment] 2015-03-19 17:19
I am not too sure you actually see a live result, since that is a compile time process. (Upgrading should purge the compiles itself, but this was buggy and was fixed by onli with a 2.0-beta version.)

But my question simply was: now that you are on 2.0.1 and you change back to the open relative path, then purge the compiles via maintenance section, what does it say after recompiling?

**Comment by donchambers** [comment] 2015-03-19 17:29
> But my question simply was: now that you are on 2.0.1 and you change back to the open relative path, then purge the compiles via maintenance section, what does it say after recompiling?

It worked!  I removed "./" leaving {include file="filename.tpl"}, saved, purged templates_c, and it now works again as before.

So, what do we do going forward?  Do we use file="./filename.tpl" because it is the same as file="filename.tpl" or do we need to do something about recompiling/purging templates_c?

**Comment by ophian** [comment] 2015-03-19 17:37
I does not hurt to use it the strict way for the public. But before getting busy on that I would think to wait for 2.0.2 and see if that happens again to you, now that you are using the open one.

**Comment by donchambers** [comment] 2015-03-19 17:49
Did something change from 2.0 - > 2.0.1 that I should expect to change again in 2.0.2?

I am a little uncomfortable waiting to see "if something happens again"...  do we have any idea why it happened?  It didn't happen only to me.  Garvin modified several themes because of this issue.

**Comment by ophian** [comment] 2015-03-19 17:57
No. Garvins issue is a symlinked issue, which is something different!

**Comment by donchambers** [comment] 2015-03-19 18:08
I guess from this point forward I will use ./filename.tpl just to avoid any potential conflict, but will report back here when 2.0.2 is released to see if it happens again for my one demo.

**Comment by yellowled** [comment] 2015-06-13 07:25
What about this? Is it a Smarty issue? Is it an issue at all?

**Comment by yellowled** [comment] 2015-12-21 10:45
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by onli** [comment] 2016-01-15 01:55
Seems like this is no issue

**Closed by onli** 2016-01-15 01:55 UTC
Labels: 2.0, bugs

**Comment by igoltz** [comment] 2017-06-09 13:37
years later...
I updated a s9y (symlinked) installation from 1.7.8 to 2.0.5 to 2.1.1 and hit this bug(?) in blogs using the kinetic theme.

Prefixing the tpl files included tpl files with ./ solves it. But digging deeper through enabling _$serendipity['smarty']->testInstall();_ in functions_smarty.inc.php I get

```
    [template_dir:Smarty:private] => Array
        (
            [0] => /var/www.serendipity/html/jugendkurse/templates/default/
            [1] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [2] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [3] => /var/www.serendipity/html/jugendkurse/plugins/
            [4] => /var/www.serendipity/html/jugendkurse/templates/default/
        )
```

which does not include the template path.
Looking at serendipity_smarty_class.inc.php (from version 2.1.1) shows that the path _$template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];_ is only included when _$template_engine_ is not definded. However it is set to "default".
If I patch serendipity_smarty_class.inc.php so that the templatePath is always included all the kintetic based blogs work again without modifying the tpl files. Non kinetic blogs work too.
As I have no knowledge of s9y interna my question is: is this patch a bad hack? Why is the template path not included, which would make sense I guess.

```
--- serendipity_smarty_class.inc.php.org	2017-04-09 09:35:14.000000000 +0200
+++ serendipity_smarty_class.inc.php.igo	2017-06-09 15:26:09.922142184 +0200
@@ -131,6 +131,7 @@
             // this is tested without need actually, but it makes the directory setter fallback chain a little more precise
             $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];
         }
+        $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template'];
         $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['defaultTemplate'];
         $template_dirs[] = $serendipity['serendipityPath'] . $serendipity['templatePath'] . $serendipity['template_backend'];

```

```
    [template_dir:Smarty:private] => Array
        (
            [0] => /var/www.serendipity/html/jugendkurse/templates/default/
            [1] => /var/www.serendipity/html/jugendkurse/templates/kinetic_jugendkurse2/
            [2] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [3] => /var/www.serendipity/html/jugendkurse/templates/2k11/
            [4] => /var/www.serendipity/html/jugendkurse/plugins/
            [5] => /var/www.serendipity/html/jugendkurse/templates/default/
        )`

```
