### ISSUE TITLE
"Invalid session hash" on 2 tab w/ and w/o login

### ISSUE THREAD

**Issue by manitu-opensource** [s9y/Serendipity#514] opened 2017-05-24 08:37 UTC
Using version: 2.1.1

Steps to reproduce:
1. Not being logged in, open a tab / window (#1)
2. Open another tab / window, login to admin (#2)
3. Write a comment in window #1 and submit it. There is a (german) message about "invalid session hash", the comment content (!) is deleted, the name and email address not.

**Comment by th-h** [comment] 2017-05-24 08:44
The comment deletion is due to #487, fixed in master and 2.1.x branch; you could patch it yourself from #503.

The "invalid session hash" seems to be another problem that's not fixed yet.

Thanks for the report!

**Comment by garvinhicking** [comment] 2017-05-24 09:11
@manitu-opensource Thanks for the report. The invalid session hash happens as part of the spamblock protection, I believe. When entering any page of the blog in another window, the session hash is updated, and the first one no longer possible. This is to reduce spam, because you cannot parallely post comments in multiple sessions. 

I think this is a configuration option of the spamblock plugin which you could even turn off, but I don't have the time right now to verify this option.

**Comment by th-h** [comment] 2017-05-24 14:32
It's named "Direktkommentare verbieten? (XSRF-Schutz".

**Comment by th-h** [comment] 2017-05-25 07:47
If one part of the reported bug is already fixed in the next (not yet released) patch version and the other part is working as designed, we should perhaps close this issue?

**Closed** 2017-05-25 07:51 UTC
Labels: backend, bugs
