### ISSUE TITLE
Plugin serendipity_event_entryproperties does not add the timeline_image field it provides for.

### ISSUE THREAD

**Issue by Maliuta** [s9y/Serendipity#671] opened 2020-01-26 17:15 UTC
Using the serendipity_event_entryproperties adds a field for "Entry Image.", with a link to the media library to add it. There is no working functionality behind this, i.e. the plugin fails to add the property which some themes go looking for.

`$ rgrep -l timeline_image
templates_c/timeline/74/52/81/745281ac00fb0c2f85bbeec58e9a62e9c007799e_0.file.entries.tpl.php
templates/timeline/entries.tpl
templates/timeline/entries_summary.tpl
templates/timeline/config.inc.php
`
`plugins/serendipity_event_entryproperties$ rgrep -l image
ChangeLog
`

I am baffled that the preview for the image is mentioned in the ChangeLog for the plugin, but a read of the plugin makes no mention of the field at all.

**Comment by yellowled** [comment] 2020-03-21 16:20
@Maliuta `timeline_image` is specific to the Timeline theme. I'm not sure if it is able to create the field automagically (I don't use the theme). You may need to create the field manually in the configuration of the entryproperties plugin.

**Comment by th-h** [comment] 2020-03-27 16:07
> Using the serendipity_event_entryproperties adds a field for "Entry Image.", with a link to the media library to add it.

AFAIS the field is added by the timeline theme, not by the entryproperties plugin.

> There is no working functionality behind this, i.e. the plugin fails to add the property which some themes go looking for.

I just tried it (current checkout of master, timeline theme, added an image), and it works for me (the image is shown). After changing the theme back to 2k11, the image (and "Entry image" field) disappears Switching back to timeline, both reappear.

Same with the current stable branch (2.3.4).

**Comment by th-h** [comment] 2020-04-11 09:03
Closed as not reproducible. - Please reopen if the problem persists (and please try to add more information - steps to reproduce - in that case).

**Closed** 2020-04-11 09:04 UTC
Labels: unreproducible
