### ISSUE TITLE
Doubling entries

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#340] opened 2015-04-20 13:13 UTC
Unfortunately, I have no clue how to reproduce the behaviour. Sometimes I write an article and save (and publish) it, after a few moments I edit something in the article that I forgot and I end up with two (published) articles.

This happens either with drafts and with published ones.

Any idea where this comes from? Autosave?

Serendipity 2.1-alpha1, PHP 5.4.16

**Comment by ddeimeke** [comment] 2015-04-20 13:30
I can reproduce it exactly the way described before.

Write an article, save it, keep the edit window open, do some changes and save it again.

**Comment by onli** [comment] 2015-04-20 14:55
That should be caused by a javascript error after saving the entry that prevents the id to be set, this code: https://github.com/s9y/Serendipity/blob/c786d457a7356b8da24d5509a92fd7650f4689f7/templates/2k11/preview_iframe.tpl#L58

Next time this happens, could you check your browser js console for errors?

**Comment by ddeimeke** [comment] 2015-04-20 17:36
I will try to remember. The problem is, that I only find out about duplicate entries once I click on "edit entries".

**Comment by yellowled** [comment] 2015-06-13 07:22
@ddeimeke This has been open for almost two months now – did you remember to reproduce what @onli suggested?

**Comment by ddeimeke** [comment] 2015-06-14 06:24
Yes, I tried to, but I never saw the duplicate entry directly after I saved an article. I only recognized them after publishing. In my opinion, the combination of autosave and preview create this issue.

**Comment by yellowled** [comment] 2015-12-21 10:45
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by ddeimeke** [comment] 2015-12-21 11:52
I did not see this behavior for a while now. Maybe you close the issue and I open a new one, once it occurs.

**Comment by yellowled** [comment] 2015-12-21 11:54
Makes perfect sense. :+1:

**Comment by onli** [comment] 2016-04-23 09:40
It occurred again.

I still can't reproduce it in my blog, test or otherwise, but we found a plan how to solve this: The moment the "Create new entry" is generated create a new entry with a proper id. The new part of this is that we could get rid of the javascript which sets the id of the newly generated into the entry editor id. But it is potentially complicated codewise. Investigate.

**Comment by yellowled** [comment] 2016-09-13 11:56
@onli Shouldn't this be fixed by the recent changes we made to the backend preview or is this unrelated to the preview?

**Comment by onli** [comment] 2016-09-13 15:19
Not unrelated, as it is caused by the JS in the save iframe not working properly. Removing the backend JS could help to reduce this, but fully solved it would only be if we follow the plan described in https://github.com/s9y/Serendipity/issues/340#issuecomment-213703697, or if we find a better solution.

**Comment by garvinhicking** [comment] 2017-04-08 10:05
(Should hopefully be fixed)

**Closed by garvinhicking** 2017-04-08 10:05 UTC
Labels: bugs
