### ISSUE TITLE
use HTTPS (not HTTP) for packages.zendframework.com

### ISSUE THREAD

**Issue by GETandSELECT** [s9y/Serendipity#418] opened 2016-08-22 13:34 UTC
error

```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (7.4M)
Staging...
-------> Buildpack version 4.3.18
Installing HTTPD
Downloaded [https://buildpacks.cloudfoundry.org/concourse-binaries/httpd/httpd-2.4.23-linux-x64.tgz] to [/tmp]
Installing PHP
PHP 5.5.38
Downloaded [https://buildpacks.cloudfoundry.org/concourse-binaries/php/php-5.5.38-linux-x64-1470848791.tgz] to [/tmp]
Downloaded [https://buildpacks.cloudfoundry.org/concourse-binaries/php/php-5.5.38-linux-x64-1470848791.tgz] to [/tmp]
Downloaded [https://buildpacks.cloudfoundry.org/php/binaries/trusty/composer/1.2.0/composer.phar] to [/tmp]
PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   283  100   283    0     0    494      0 --:--:-- --:--:-- --:--:--   494
Loading composer repositories with package information
                                                                                                                                                                           
  [Composer\Downloader\TransportException]                                                                                                                                 
  Your configuration does not allow connections to http://packages.zendframework.com/packages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.  
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
-----> Composer command failed
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/scripts/compile.py", line 50, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/builder.py", line 208, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
    return composer.compile(install)
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 316, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 360, in run
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/runner.py", line 109, in stream_output
build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7fc160f646f0>' returned non-zero exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Successfully destroyed container

FAILED
BuildpackCompileFailed
```

fix (was HTTP, new HTTPS)

```
$ cat composer.json 
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.zendframework.com/"
        }
    ],
    "require": {
        "php": ">=5.3.3",
        "zendframework/zend-db": "2.*",
        "katzgrau/klogger": "1.0.*"
    },
    "config": {
        "vendor-dir": "bundled-libs"
    }
}
```
<img width="719" alt="screen shot 2016-08-22 at 15 39 54" src="https://cloud.githubusercontent.com/assets/10598483/17856643/c8e28514-687e-11e6-9ea7-267244b0415b.png">

**Comment by onli** [comment] 2016-08-22 21:39
Thanks for the report! I applied your patch and will close this issue. Please report back if the problem is not solved.

**Closed by onli** 2016-08-22 21:39 UTC

**Comment by GETandSELECT** [comment] 2016-08-23 20:02
thanks @onli

**Comment by flik** [comment] 2018-10-12 11:54
Here is simple solution:
`composer config -g secure-http false`
