### ISSUE TITLE
wrong authorid by certain image upload

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#264] opened 2015-01-16 14:31 UTC
Please read #263 on how I did this.

Hey, I just saw my small image jpg upload produced an authors title, which is
https://github.com/s9y/Serendipity/blob/2.0/templates/2k11/admin/media_items.tpl#L59
and should **not** happen! So there must be a missing or wrong authors id around to make this happen...

In the serendipity_image table it is placed as authorid 1. Is that intended to happen here? I assume, Not!

Apart from this is a bug, this becomes important when you need a static sized `clearfix equal_heights media_file_wrap` block. while then you have images with and without the authors name span, which expands the grey media box.

**Comment by garvinhicking** [comment] 2015-01-16 14:36
Probably an issue with the EXIF metadata of the JPEG? Else, the authorid with which you uploaded is not #1? Which is your authorid?

**Comment by ophian** [comment] 2015-01-16 14:36
All other have 0.

**Comment by garvinhicking** [comment] 2015-01-16 14:42
What's the difference between the images with a 0 and a 1, what was done differently? How is it reproducible?

**Comment by ophian** [comment] 2015-01-16 14:44
It is reproducible and happens when you upload an image with max-width set to 100 and use the Resize before Upload option.

**Comment by yellowled** [comment] 2015-01-16 14:48
Guys, after @onli mentioned in the forums that “Resize before upload” isn't done anyway, I feel like this is maybe not *that* important/should be discussed tomorrow to get more info on “Resize before upload”?

**Comment by ophian** [comment] 2015-01-16 14:54
right one with max-width 100 **and** Resize before Upload option, left with that option disabled (which needs to upload an image <= than the allowed max-width 100 set).
![wrongauthorid](https://cloud.githubusercontent.com/assets/1105372/5777940/5dfa7936-9d97-11e4-9515-79426172f4b9.png)

**Comment by onli** [comment] 2015-01-16 17:32
I saw that bug before, it definitely happens. No idea why.

**Comment by ophian** [comment] 2015-01-16 18:15
It seems the authorid 0 needs an client-server authentification which cannot pass with this js resize uploader. Thus it falls back to 1, I assume. Uploading this way takes other id permisssion levels correctly. (I added a chief editor user and did this. He can set max-width but has no js resize option on its own.) 

[**hijack mode:** We should check permission levels in configuration, btw. My Chief Editor is able to....]

**Comment by garvinhicking** [comment] 2015-01-17 14:38
I'll check this issue out and see, maybe really related to EXIF or permissions, or whatever.

**Comment by ophian** [comment] 2015-01-18 18:17
I think I have found the cause of that "wrong" authorID issue. 
Its done here https://github.com/s9y/Serendipity/blob/2.0/include/admin/images.inc.php#L171.

The JS Uploader  script https://github.com/s9y/Serendipity/blob/2.0/templates/2k11/admin/serendipity_editor.js.tpl#L1384 is missing a hidden POST var like this one https://github.com/s9y/Serendipity/blob/2.0/templates/2k11/admin/media_upload.tpl#L85, which btw is in question, since that should not always be true, shouldn't it?

**Comment by onli** [comment] 2015-01-18 18:29
Nice find, that should be it. Think to set all authors by default is sound. Do you want to commit the patch?

**Comment by ophian** [comment] 2015-01-18 19:09
> Do you want to commit the patch?

No.

And where is the all_authors perm set back then?

**Comment by onli** [comment] 2015-01-18 19:34
Should be fixed now

**Comment by garvinhicking** [comment] 2015-01-19 09:22
@ophian Many thanks for finding this! That saved me some time!!!)

This "all_authors" stuff is AFAIR a leftover thing, in older s9y versions. Sadly, berlios SVN is no longer available so I cannot actually look up the history of the file (DAMN!). I believe we had that to specify if images are only available to one author, but I think users said that this is a feature that messed up things, and the media library was changed to put read-privileges based on media directories instead of individual files.

So probably we could even patch the code in the PHP file to always insert "0" as the authorid...?!

**Comment by ophian** [comment] 2015-01-19 10:15
The funny thing is, before this, I actually thought `0` to be some sort of superuseradmin, but as we can see now, it is meant as "not set authorid", available for all. And another, that the JS upload seems to be somehow used, even if no max options are set

I think it is still a good idea to have author rights given on images, which now does not work any more, since this currently seems to always uploads images as 0, even when logged in as someone else. [Erm...wait... I check this up more detailled tonight]

**Comment by yellowled** [comment] 2015-01-19 10:18
We should probably agree to check and revise the groups and their permissions for Future, but not let this hold up Stable?

**Comment by garvinhicking** [comment] 2015-01-19 11:12
Images are not based on authorids anymore since at least serendipity 1.3 or 1.4, so this is a long time, and it would really not be a hold-up/blocker for 2.0.

I really thing per-image permissions are too clumsy, each SQL query would need to be checked and in reality editors should use their common pool, possible with specific personal directories...

I close this issue for now, if there are discussable reasons for why this should happen we should split this into a new issue.

**Comment by ophian** [comment] 2015-01-20 09:18
> Images are not based on authorids anymore since at least serendipity 1.3 or 1.4,

So .. then the authorid line should be dropped or changed to 0 overall. See media_items and the $authorid setter etc

**Comment by garvinhicking** [comment] 2015-01-20 09:45
@ophian I agree. We should do this for the 2.1.x series. I reopened this issue to address this.

**Comment by garvinhicking** [comment] 2015-01-27 13:22
Committed as 253428d

**Closed by garvinhicking** 2015-01-27 13:22 UTC
Labels: 2.0, backend, bugs
