### ISSUE TITLE
Theme-List display error in Firefox

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#485] opened 2017-04-12 09:58 UTC
**Reproduce:** Might have to set 2k11 as the theme to reproduce, see screenshot below. The error was reported by @ddeimeke in current Firefox (52, I assume) on Linux and Firefox 45 ESR on Windows. I can *not* reproduce it in Firefox 52 on either macOS or Windows 10, so it might be an edge case.

![2017-04-12_091207](https://cloud.githubusercontent.com/assets/326223/24952269/3fc58bcc-1f77-11e7-89f7-8573ee9a8b0d.png)

So the first question would be if anyone can replace this on Linux or Windows.

**Comment by th-h** [comment] 2017-04-12 12:36
Can't reproduce either (Win 10, FF 52.0.1 EU).

**Comment by onli** [comment] 2018-06-12 21:10
Since no one seemed to be able to reproduce this for a long time now I will close this, highly likely that this was fixed by a browser update. If not, please reopen.

**Closed by onli** 2018-06-12 21:10 UTC
Labels: backend, bugs, interface, templates
