### ISSUE TITLE
Installation does not check for mysqli extension

### ISSUE THREAD

**Issue by ecki** [s9y/Serendipity#449] opened 2017-02-11 02:00 UTC
On my 2.4 Apache on FreeBSD I had to install the php56-mysql and php56-mysqli extension. The installer was not checking if it is available. Actually the install worked but the first blog visit failed with `undefined function mysqli_connect`

Noticed this with a fresh 2.1rc1

**Comment by garvinhicking** [comment] 2017-04-08 10:17
We actually checked this on a freebsd installation with the 2.1 candidate. When mysql/mysqli was not installed, we could not select it in the dropdown in the installer, so this was working as intended.

Did you maybe move a already installed s9y installation or change the packages in between installation? We'll close this for now because it's not reproducible to us, if you have details feel free to reopen. Thanks!

**Closed by garvinhicking** 2017-04-08 10:17 UTC
Labels: blocking, bugs

**Comment by ecki** [comment] 2017-04-08 10:27
Hm, it was a new installation but with an pre-existing database (and local config), so yes this could explain it. I just noticed that other missing php extensions have been printed. I guess the dropdown was then enabled cause it was selected in the local settings (I don't remember the sequence of Installation anymore clearly). However, of the stepmtomverify extensions is after the dB config selection it would not hurt to explicitly check for the extension as well. I try to re-create the order and re-open in case I am sure it was natural.
