### ISSUE TITLE
Implement default "404" content message

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#421] opened 2016-09-20 08:39 UTC
http://board.s9y.org/viewtopic.php?f=2&t=20861&p=10446106#p10446106

@onli  can you have a look? I committed a patch for this already.

**Comment by onli** [comment] 2016-09-20 18:59
I'm running in two problems here, but I don't think they are related directly to your changes:

 1. When just modifying an entry link to an invalid id I see the new content message (well, the variable). But in my testblog I do not get sent to the frontpage, instead I'm on an empty article page.
 2. It also trigger an sqlite error: `Error in SELECT count(e.id) GROUP BY e.id`
 3. When I go to index.php?/abc, I see the main page without a 404 error code set.

Does it work as expected for you? Then I'm running in specific problems with my setup and we can fix that later. But if you see the same strange behaviour, then the default 404 detection and redirect is a bit broken currently.

**Comment by garvinhicking** [comment] 2016-09-21 09:19
Thanks for chiming in:

1: That's true, simply be changing the ID, s9y stays in the article detail mode, I did not make a change to that (this would be much more complex)

2: That should  have been the case also before the patch, yes

3: My patch doesn't really change/watch the supplied URL parameters. "index.php" is a valid URL, and would never trigger the actual 404 error. I only changed when you have URL rewriting on and you call like "blog.example.com/blabla/dudu.html" which then would show the frontpage...

**Comment by onli** [comment] 2016-09-21 09:36
Yes, I thought that your code can't be responsible here, I just wasn't sure whether the routing changes might be :) In that case let's consider these issues later, we can extend the 404 mode for the next version.

**Comment by yellowled** [comment] 2016-12-02 14:27
In my dev blog (2.1-beta3), this emits both the 404 content message as well as the content on static pages. See http://s9y.netzgestaltung.net/styleguide.html, for example. I was baffled to see this since it does *not* happen on Dirk's blog, which also runs 2.1-beta3. I even tested it with 2k11 to rule out that it is related to the theme.

However, it does *not* happen if I disable URL rewriting. So maybe the 3. part is not quite there yet.

**Comment by donchambers** [comment] 2017-01-02 03:19
Hi guys.  Happy New Year to everyone.

I just installed the latest s9y from Github.  All static pages now display the same message as @yellowled  mentions above.

This message does NOT appear in a static page preview.

I am happy to assist in testing a solution.

**Comment by garvinhicking** [comment] 2017-01-02 08:52
@donchambers @yellowled I have fixed the error in staticpage plugin 2.15...I couldn't see a better fix for this other than within the plugin tho. I would love to have been able to change it in the core. Maybe @onli who worked on the routing a few months ago has an idea up his sleeve? :)

**Comment by yellowled** [comment] 2017-01-02 09:28
Fix works for me.

**Comment by donchambers** [comment] 2017-01-03 16:20
Yes, it eliminates the message.  Is there ever the possibility of a legitimate $content_message on a static page that will not now be seen, or is that not ever possible?

**Comment by onli** [comment] 2017-02-11 14:48
That might still be broken. See https://board.s9y.org/viewtopic.php?p=10446654#p10446654:

> Ich verwende 2k11. In der Navigation sind zum Teil statische Seiten angegeben. Bei denen erscheint der > richtige Inhalt, oberhalb wird aber diese Meldung gezeigt:
> 
>  `Die angeforderte Seite konnte nicht gefunden werden (404). Dies ist die Standardseite.`

http://u1amo01.de/blog/pages/audio.html shows the problem.

**Comment by yellowled** [comment] 2017-03-22 08:15
Also, it seems to happen for contact form pages as well now. See [forum post](https://board.s9y.org/viewtopic.php?p=10446937#p10446937) and [live example](http://www.optional-necessity.com/demo/timeline/pages/contactform.html) by @donchambers.

**Comment by donchambers** [comment] 2017-03-27 14:10
Using the staticpage modification by Garvin, I have added this at line 369 in my local copy of serendipity_event_staticpage.php:

`        $serendipity['content_message'] = ''; // Reset message for 404 error handling which is now overriden`

Does anyone think there is a better way to handle this?

**Comment by donchambers** [comment] 2017-03-28 02:32
Correction:  serendipity_event_contactform.php.  Sorry.

**Comment by donchambers** [comment] 2017-03-29 02:11
@garvinhicking  & @onli - can you guys provide an opinion on this?  Thanks!

**Comment by onli** [comment] 2017-03-29 09:42
@donchambers I just don't get this reproduced. In my devblog everything works as it should. But if @garvinhicking doesn't have an idea, maybe we should revert this change for the next RC or the stable.

**Comment by onli** [comment] 2017-03-29 09:50
@donchambers I kind of missed where you are. The change you did for the contactform-plugin will be necessary. Not that i know that plugin, but it looks to behaves like staticpage, thus it needs the same code. I think you should add the patch to the spartacus version and bump the version.

**Comment by donchambers** [comment] 2017-03-31 02:30
@onli - per your suggestion, I patched the files - current version should be 1.21

**Comment by garvinhicking** [comment] 2017-04-08 09:31
Cool, thanks! :)

**Comment by yellowled** [comment] 2017-04-16 16:31
We might not be done with this, see https://board.s9y.org/viewtopic.php?p=10447101 (German).

**Comment by mariohommel** [comment] 2017-04-16 18:27
Error comes from serendipity_event_custom_permalinks which seams to have the same problem as staticpages and contactform.

**Comment by yellowled** [comment] 2017-04-16 19:05
If so, I can not reproduce that in a quick test.

**Comment by mariohommel** [comment] 2017-04-16 19:10
I installed serendipity_event_custom on http://vps.hommel-net.de/serendipity/ and created a new entry with a special permalink. The article page of this entry throws the error, other article pages don't.
http://vps.hommel-net.de/serendipity/permalink/eintragperma.html

**Comment by yellowled** [comment] 2017-04-16 19:21
Same thing on my dev blog – new entry with custom permalink, **no** 404 error. http://s9y.netzgestaltung.net/custom-permalink.html

**Comment by mariohommel** [comment] 2017-04-16 19:24
Maybe it's the additional path "permalink" on my site?

**Comment by yellowled** [comment] 2017-04-16 19:25
Nope. http://s9y.netzgestaltung.net/permalink/test.html

**Comment by mariohommel** [comment] 2017-04-16 19:40
Could this be something that has been fixed in 2.2.0beta?

**Comment by yellowled** [comment] 2017-04-16 19:42
I wouldn't know – @onli @garvinhicking, is there something™ in 2.2.0-beta1 that's not in 2.1.1 that could fix this?

**Comment by mariohommel** [comment] 2017-04-17 07:10
I insertet 
`$serendipity['content_message'] = ''; // Reset message for 404 error handling which is now overriden`
at line 128 of serendipity_event_custom_permalinks.php in my testblog and the error message doen't come up anymore.

**Comment by yellowled** [comment] 2017-04-17 07:36
Patched the plugin accordingly. Still wondering why I can not reproduce this in 2.2.0-beta1.

**Comment by onli** [comment] 2017-04-17 13:07
>  is there something™ in 2.2.0-beta1 that's not in 2.1.1 that could fix this?

Nothing I can think of, or see in the commit log :/

**Comment by mariohommel** [comment] 2017-06-11 11:59
There's a hint at the forum that the order of the plugins could be reponsible for this behavour. https://board.s9y.org/viewtopic.php?p=10447403#p10447403

**Comment by th-h** [comment] 2018-09-30 09:28
What's the status of this issue? Is it still reproducible?

**Comment by th-h** [comment] 2019-04-27 14:10
Seems to be fixed, see https://board.s9y.org/viewtopic.php?p=10447403#p10447403.

**Comment by yellowled** [comment] 2019-09-20 18:15
Reopened 'cause https://board.s9y.org/viewtopic.php?p=10452398#p10452398 reports similar errors for `erendipity_event_cal` and `serendipity_event_guestbook` 🙄

**Comment by th-h** [comment] 2020-03-31 17:51
I tried to test that, but both plugins are not working for me (current master, running PHP 7.3.11). `cal` reports it is missing it's database table (and seems to have a really, really, REALLY terrible frontend UI), and `gustebook` throws PHP errors instead of displaying the configuration screen.

I'd tend to retire both plugins ...

**Comment by th-h** [comment] 2020-04-18 21:47
The problem was not reproducible on the linked forum thread, and both plugins seem to have lots of more pressing problems. Closing here for now.

**Closed by th-h** 2020-04-18 21:47 UTC
Labels: discuss, enhancements
