### ISSUE TITLE
next page leads to first page of search results

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#269] opened 2015-01-21 09:32 UTC
This is errornous behaviour.

In case you search something in a blog, say "flattr" in my blog:
http://www.deimeke.net/dirk/blog/index.php?serendipity[action]=search&serendipity[searchTerm]=flattr&serendipity[searchButton]=Los!

You get a link for "next page" at the bottom of the search results, which is correct. Next page leads to page1, see
http://www.deimeke.net/dirk/blog/index.php?/search/flattr/P1.html

There is no possibility (no link) to the second page of search results:
http://www.deimeke.net/dirk/blog/index.php?/search/flattr/P1.html

Please have a look.

**Comment by yellowled** [comment] 2015-01-21 09:43
Not sure I get what's the issue here.

The search results message says 20 entries. There's 5 entries on page 1, 15 on page 2. So from page 2 on, it's no longer split into the number of entries you set in the configuration?

**Comment by ddeimeke** [comment] 2015-01-21 09:51
Interesting.

I get 15 direct results for the search and I would expect to get the remaining 5 klicking on next page, but it leads to "*/P1.html" which is the first page of results. "*/P1.html" does not show any "next page" link.

Please click the links in the first posting.

**Comment by ophian** [comment] 2015-01-21 09:55
I think it is because you use the option @onli has onces integrated to Serendipity, called "Stable Archives". The next page (and in this case last page) should be http://www.deimeke.net/dirk/blog/index.php?/search/flattr/P2.html
It should IMHO never be P1 for this option.

**Comment by yellowled** [comment] 2015-01-21 09:56
Indeed, reproducable from clicking the links in your original post. I have no idea how I got to 5/15 the first time. o_O

**Comment by garvinhicking** [comment] 2015-01-21 10:00
Yes, "Stable Archives" should be the culprit, maybe it's easy to fix @onli ? I'm too afraid to break something because I was already afraid of touching the sort order in first place ;)

**Comment by garvinhicking** [comment] 2015-01-21 10:01
Maybe it can simply be disabled when searchmode is active?!

**Comment by ophian** [comment] 2015-01-21 10:06
Or use searchresults +1 ever, if the option is set ... ;-)

**Comment by ddeimeke** [comment] 2015-01-21 10:20
I disabled stable archive and it works as expected including P1 and P2.

I second Garvins suggestions to disable the feature for search results.

**Comment by onli** [comment] 2015-01-21 10:32
There are two options: One is to look at how the next link is constructed by the template. It's possible that is hardcoded, or that the core is giving the wrong information. The other is two disable the stable sort order for search results, which should be easy enough. I'll look at it.

**Comment by onli** [comment] 2015-01-21 17:59
Should now be fixed in 2.0 and master. I just disabled the pagination navigation changes when doing a search, so it should behave exactly like without the option activated.

**Comment by ddeimeke** [comment] 2015-01-21 20:07
Works for me, everything is good now. Thank you.

**Comment by garvinhicking** [comment] 2015-01-21 20:21
Sorry I misconmmented under the commit instead this issue:

@onli I believe this needs more adaption because the "search" pattern is user-configurable as a permalink. Maybe better check for $serendipity['GET']['action'] == 'search' which should be set in index.php?

And could you document in NEWS?

**Comment by onli** [comment] 2015-01-22 09:23
I wasn't aware of that. Yes, that would be better.

**Comment by onli** [comment] 2015-01-22 18:52
Ha, I'm not used to the github commit commands working. It's nice working on master ;) 

But that should indeed be better fixed now, so I'll let this closed. Please reopen if I'm wrong about that.

**Comment by yellowled** [comment] 2015-01-22 18:55
There is a **lot** you can do with these (on GitHub). For instance `References s9y/Serendipity#269` from a commit in s9y/additional_plugins should reference your commit cross-repository.

**Comment by yellowled** [comment] 2015-02-02 12:26
In my new dev blog (running on `master`), this still seems to have issues. I have “Stable Archives” set to “Yes”, blog set to display 5 entries per page.

When I click “next page” on the index page, the second page contains only 1 entry. It also emits the related entries of said entry (from freetags), which is not supposed to happen. The following pages work fine.

**Comment by yellowled** [comment] 2015-02-02 12:28
Also, if I do a search on the test blog which reports 8 hits, the second page is empty.

**Comment by onli** [comment] 2015-02-02 13:20
> When I click “next page” on the index page, the second page contains only 1 entry.

That is expected behaviour. You always need one page to shrink, and since the frontpage is not available for that, the second does that.

>  It also emits the related entries of said entry (from freetags), which is not supposed to happen. 

I can imagine why - he might think he is on a single page display because only one entry is shown. That would be a template bug though, I'd suggest to move that into a separate issue.

> Also, if I do a search on the test blog which reports 8 hits, the second page is empty.

That is strange, because that already worked, and the search should completely mirror the behaviour of not having stable archive enabled. Current git checkout? It is showing 5 entries? I will see whether I can reproduce it.

**Comment by yellowled** [comment] 2015-02-02 13:27
> That is expected behaviour.

For the user or visitor of the blog, it's more like confusing behaviour.

> That would be a template bug though, I'd suggest to move that into a separate issue.

Will do.

> Current git checkout? It is showing 5 entries?

Current `master`, it is showing 5 entries on the first results page, but none on the second (with 8 results in total according to the search results message).

**Comment by yellowled** [comment] 2015-02-02 13:30
> I can imagine why

I took the liberty of assigning #286 to you. :)

**Comment by onli** [comment] 2015-02-02 13:35
> For the user or visitor of the blog, it's more like confusing behaviour.

Sure, it might be a tad confusing for people strongly accustomed to classical blogs. I doubt that anyone else cares. If you see it as highly confusing for your visitors, you can't have a stable archive. That is the whole idea of it: to have stable archive pages for old entries, you have to have one page before that shrinks, there is just no other way. Seriously, try to model how that works, why the archive page numeration before were unstable in the first place, and how the solution now solves that.

One could of course use use the frontpage though, but in s9y that would collide with too many assumptions/options.

I can have a look at #286, but probably it is just "don't go in single entry mode when you are in a search"

**Comment by yellowled** [comment] 2015-02-02 13:41
> to have stable archive pages for old entries, you have to have one page before that shrinks, there is just no other way

Yeah, I get that, and personally, I don't even care. I highly doubt that many users even *use* search or prev/next page in my blog, and the overall use of both features is probably limited.

It it confusing as a reader, though, because it is something you don't see in *any* other blog engine. But since it's a technical necessity …

**Comment by onli** [comment] 2015-02-02 13:46
We could sell it as an unique seo improvement ;) (which it probably is).

Ok, I'll have a look at whether the search shows several pages, when stable archive enabled and emitting results for only two pages.

**Comment by onli** [comment] 2015-02-23 19:55
The thing with the related entries was not actually a template issue and also not really related to the stable archive, it was coded this way in the plugin. So I fixed that.

The issue with the stable archive I can't reproduce. It just works for me - the search result page shows exactly the entries it should and the next/prior page buttons lead where they should to.

**Comment by yellowled** [comment] 2015-02-23 20:09
> the search result page shows exactly the entries it should and the next/prior page buttons lead where they should to
Interesting: I can' reproduce that any longer, either. However, I'm not sure if I used the same search term. Actually, I don't even have the “one article on second page” thing any longer – that displays 4 articles now, although the blog is set to 5 per page …

Anyway, I guess we can close this, at least for the time being.

**Closed by yellowled** 2015-02-23 20:09 UTC
Labels: 2.0, bugs
