### ISSUE TITLE
uploadResize needs image check

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#353] opened 2015-07-07 17:31 UTC
and does not respect other object files to pass through!
See http://board.s9y.org/viewtopic.php?f=10&t=20437

**Comment by onli** [comment] 2015-07-07 18:48
The problem seems to be that other files than images lead to a JS-error and can then not be uploaded.

**Comment by yellowled** [comment] 2015-12-21 10:45
Xmas issue cleanup – this issue has been open, but without interaction for a while now. Is it still an issue? Has anyone tested or reproduced it? Should/can we close it?

**Comment by onli** [comment] 2016-01-15 02:15
I work on it.

**Closed** 2016-01-15 12:29 UTC
Labels: 2.0, backend, bugs, master
