### ISSUE TITLE
Net_DNSBL requires Net/DNS.php

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#486] opened 2017-04-12 11:58 UTC
With commit 78de4c894baaaf2112bf82bf3542c4bc90653c16 `bundled-libs/Net/DNSBL.php` was updated to 1.3.7, now requiring Net::DNS:

    require_once 'Net/DNS.php'

Unfortunately, this library is *not* bundled ...

So Net_DNSB (and s9y) fails with "Fatal error" when using `serendipity_event_spamblock_rbl` for comments. Not really helpful. :)

**Comment by yellowled** [comment] 2017-04-12 17:43
Duplicate of #459

**Closed by yellowled** 2017-04-12 17:43 UTC
Labels: bugs, plugins
