### ISSUE TITLE
Non-image subtome

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#285] opened 2015-02-02 09:37 UTC
Reproduce (in `serendipity_plugin_syndication` config):

* Set option “Feed-Icon” to “none”
* Set option “subToMe” to “yes”

I would expect this to emit a plain text link to the RSS feed (which themes could style differently). Instead, it emits a link with `.serendipity_xml_icon` wrapped in the same link. That's redundant code.

Proposed markup for these settings:

```
<a id="serendipity_subtome_plain" href="/feeds/index.rss2" onclick="document.subtomeBtn=document.querySelector('#serendipity_subtome');document.subtomeBtn.dataset['subtomeFeeds']='%2Ffeeds%2Findex.rss2';var s=document.createElement('script');s.src='https://www.subtome.com/load.js';document.body.appendChild(s);return false;">RSS Feed</a>
```

**Comment by garvinhicking** [comment] 2015-02-11 13:42
(I took the liberty to assign @onli to this issue just because he'd probably be most proficient about subtome :) )

**Comment by yellowled** [comment] 2015-02-11 13:46
Should not be a release blocker, either.

**Comment by onli** [comment] 2015-02-23 20:14
I reproduced it. It seems to be easy code- and markup-wise, but is complicated in total.

The option *Feed-Icon* controls the big feed icon only. That is not the same thing as the small xml icon from `.serendipity_xml_icon`, controlled in the next step of the configuration. 

I actually already tried once to go in the direction you propose, to have only one link (I kept the xml icon though). That wasn't accepted cause then the category plugin looks different.

So, since we shouldn't change that list for users who by choice try to reproduce the old s9y look, we shouldn't do this. We could however make it possible to set the xml-icon option to *none* as well, and only show the plain textlink then.

**Comment by yellowled** [comment] 2015-02-23 20:20
> We could however make it possible to set the xml-icon option to none as well, and only show the plain textlink then.

If that's the only option (and it sounds as if it is), then I guess that's the way to go.

**Comment by onli** [comment] 2015-02-23 21:07
Added. And while doing that found out that there still was a bug in the code. You should test it thoroughly before closing here.

**Comment by yellowled** [comment] 2015-02-23 22:05
```
Parse error: syntax error, unexpected ':' in /var/www/virtual/user/domain.tld/plugins/serendipity_plugin_syndication/serendipity_plugin_syndication.php on line 196
```

**Comment by yellowled** [comment] 2015-02-23 22:07
That also breaks the plugins section of the backend, BTW.

**Comment by onli** [comment] 2015-02-23 22:22
-.- 
Thanks. e310786 fixes that for me.

**Comment by yellowled** [comment] 2015-02-23 22:44
Yes, it does.

I still don't like the inline JS on the subtome links, but I forgot if we already discussed this. It isn't part of this issue anyway, so nevermind.

Going to add a small fix for the syndication plugin myself in a minute an then close it, other than that it looks good to me.

**Comment by yellowled** [comment] 2015-02-23 22:51
@onli I don't see the specific reason why you did not completely backport this to `2.0` yet …? Did you just want to wait for me to test it?

**Comment by onli** [comment] 2015-02-24 08:52
I don't want to add new features to 2.0.1, so I only backported the bugfix.

**Comment by ophian** [comment] 2015-06-08 07:56
I think there is more to figure out. Please check.

1. Master and 2.0 branch differ in markup of output, see anchor, w/o id.
2. Bulletproof blue_style (probably other coloured styles do the same) doubles the replace icons for the img and the link. http://board.s9y.org/viewtopic.php?f=3&t=20228

**Comment by yellowled** [comment] 2015-06-08 08:06
Seems as if the text link must not have `serendipity_xml_icon` if there is a subtome link in front of it, but that might only be in Bulletproof. Also, *all* the img links seem to have `id="subtome"`, which of course is invalid markup.

However, looking at the blog post I wonder (haven't tested it yet) if the forum OP maybe has a broken plugin or installation because the settings do not match the emitted markup in his blog at all. (That might, however, be because he changed them in the meantime.)

**Comment by yellowled** [comment] 2015-06-08 08:14
Yeah, he definitely does have an outdated version of the plugin. The current one (which in my case is a git checkout, but still) now emits `serendipity_subtome` as a class. And I just tested it with BP blue, it does not have the duplicate icon there.

**Comment by ophian** [comment] 2015-06-08 08:32
Thats what I said in 1. Master and 2.0 branch differ.

**Comment by yellowled** [comment] 2015-06-08 08:35
Oh, right. For some reason, my brain was thinking my dev blog runs on 2.0. Sorry. Monday.

**Comment by yellowled** [comment] 2015-06-08 08:50
Well, either way – it is not an issue in BP, it's an issue in the plugin which is fixed in `master`. I *assume* it is in fact only exposed in BP, at least I'm not aware of other themes that use this technique to switch xml icons in syndication. (Well, Kinetic and other BP derivates, probably.)

The question is whether this is significant enough to backport it to 2.x.

**Comment by ophian** [comment] 2015-06-10 10:37
@onli Please check this 2.0.2 suggestion and upport to master

**Comment by onli** [comment] 2015-06-10 11:28
@ophian The bug was already fixed in master?

**Comment by onli** [comment] 2015-06-10 11:41
I added some comments to the commit. I don't think all those changes belong in a bugfix release, and I do not want to port it like this to master. Especially if the bug was already fixed there, then I don't see the purpose of this at all.

But to use `this` in the onclick-handler might be a really good idea, I'd have to test this. I remember that didn't seem necessary, but that was probably when subtome was always only enabled for the main button. So far that seems like a good catch, thanks Ian.

**Comment by ophian** [comment] 2015-06-10 12:34
> But to use this in the onclick-handler might be a really good idea

yeah, I borrowed this from master, since that seemed a good idea. I don't use subtome, so I did not test it.

**Comment by ophian** [comment] 2015-06-16 09:47
fixed in both branches

**Comment by onli** [comment] 2015-06-16 19:58
I cleaned that up a bit. Re-open please if I missed something (tested in 2k11 and bulletproof blue).

**Comment by onli** [comment] 2015-06-16 19:58
I cleaned that up a bit. Re-open please if I missed something (tested in 2k11 and bulletproof blue).

**Closed by onli** 2015-06-16 19:58 UTC
Labels: 2.0, discuss, plugins
