### ISSUE TITLE
multiple plugin updates - do not fallback

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#279] opened 2015-01-26 13:02 UTC
Stick onto update page after plugin update submit, as long as there is more to do (say, more updates are available).

**Comment by yellowled** [comment] 2015-01-26 13:12
You mean instead of going back to the *Plugins* page, go back to *Update [Group] plugins* page if there are more updates available?

+1

**Comment by bauigel** [comment] 2015-01-26 13:14
>
> You mean instead of going back to the *Plugins* page, go back to *Update
> [Group] plugins* page if there are more updates available?
>
> +1
>

​+1​

**Comment by onli** [comment] 2015-01-26 15:58
I rather think we should have a button there  to update all plugins at once. That can be done with javascript that clicks the buttons and waits till the update is doen before clicking the next, or in core or spartacus with a function queuing the updates. Both ways are valid and should be easy enough, this modification here would probably even be more difficult.

Also, to sometimes go to the plugin page or sometimes not does not sound good/consistent, even though I get why this might be helpful in this specific case.

**Comment by yellowled** [comment] 2015-01-26 16:14
> I rather think we should have a button there to update all plugins at once.

What if you don't *want* to update **all** plugins at once? Then it would still be nice to be redirected back to the update page in case you'd want to update multiple plugins, but not all of them.

**Comment by onli** [comment] 2015-01-26 16:17
Did you ever want to not update all of them? :)

We could make them selectable, but I really doubt that case happens often enough to warrant the effort. Given that the "update all" approach works. If not, to try to be smart to which page we go afterwards would be better than now I guess.

**Comment by yellowled** [comment] 2015-01-26 16:18
> Did you ever want to not update all of them?

Yes.

For example, we have been holding off on updating the EasyPodcasting plugin in the InfoCamp blog. I forgot why, but there was a reason.

**Comment by garvinhicking** [comment] 2015-01-30 13:27
IMO this should be something for 2.x.0, not a point 2.0.1 release. 2.0.1 should only get well-tested bugfixes, but everything that could create probable trouble should be put to 2.1.0 (were we already have somet hings like that)

**Comment by yellowled** [comment] 2015-01-30 13:32
Agreed, but I don't think “well-tested” is a good criterion for this. This *is* well-tested, but it's not a bugfix.

**Comment by onli** [comment] 2015-01-30 13:35
Let's follow http://semver.org/
2.0.x: bugfixes
2.x.0: new features
X.0.0: Updates with bc-breakage/API-change

**Comment by yellowled** [comment] 2015-01-30 14:00
For issue assignment, the semver policy is fine, but I think it's too complicated for us in terms of branch management. So we should stay with `master`, `2.0` and feature branches for bigger stuff that might break things or be thrown away after discussion.

Something else I wanted to suggest: I have very good experience with naming feature branches after the related Github issue. Makes it easier to see what a feature branch is all about. So @onli's branch would have been named `279-update-all` or something like that.

**Comment by onli** [comment] 2015-02-23 19:56
I'll close here for now, I think the button works for the usecase.

**Comment by ophian** [comment] 2015-02-24 09:41
I would like to know if my origin request is closed with this also? 
All I wanted, was to singulary choose which plugins to update and the need to auto-fallback to the plugin upgrade page, as long as there are upgrades available.The new js feature updateAll is something different and not what I asked for!

Another thing. Does this new auto all upgrade routine now removes/disables the upgrade to config hooks, eg `backend_plugins_update`? Then this would break plugin update concepts we already use.

**Comment by yellowled** [comment] 2015-02-24 09:56
> to singulary choose which plugins to update

Do you mean something like selecting multiple plugins with checkboxes like you can do i.e. with comments? Because I did not get that from the original issue text.

> to auto-fallback to the plugin upgrade page, as long as there are upgrades available

Can't remember if that's the case with updating multiple plugins, but it's not the case with updating single plugins (using their update button).

**Comment by onli** [comment] 2015-02-24 11:09
@ophian Your original idea I understood as going back to the plugin update page after an update if there are still other updates. That would've been an improvement, but is not better than the new button. If there are multiple updates, users are expected to click the update all button. It solves the same use case in a better way.

> Does this new auto all upgrade routine now removes/disables the upgrade to config hooks, eg backend_plugins_update?

No

**Comment by yellowled** [comment] 2015-02-24 11:21
> Your original idea I understood as going back to the plugin update page after an update if there are still other updates.

Yet that still does not happen if users opt to use the Update button for single plugins, which is technically still possible – and might make sense – even if the Update All button is there.

**Comment by ophian** [comment] 2015-02-24 11:32
> Do you mean something like selecting multiple plugins with checkboxes like you can do i.e. with comments? Because I did not get that from the original issue text.

No. I meant "update one by one and do not fall back to another backend page than the upgrade plugin list", except in the case if the 1.7 Series new backend upgrade hooks to force a immediate fallback to a certain (config) page are used.

I still want to be able to upgrade on my personal demand, choice and time -  one by one.



>> Does this new auto all upgrade routine now removes/disables the upgrade to config hooks, eg backend_plugins_update?
>
> No

How do you know? Did you really test these cases?

**Comment by onli** [comment] 2015-02-24 12:26
The update all button is pure javascript, clicking on the other buttons one by one. Thus there is no change.

>  Yet that still does not happen if users opt to use the Update button for single plugins, which is technically still possible – and might make sense – even if the Update All button is there.

Sure. But we have to choose between the comfort in this specific case and the inconsistencies introduced by going to different places depending on the state of the system. I'm convinced it is better to workaround that.

**Comment by yellowled** [comment] 2015-02-24 12:30
> But we have to choose between the comfort in this specific case and the inconsistencies introduced by going to different places depending on the state of the system.

I don't understand how that stops us from implementing “go back to the Update plugins page after updating a plugin unless the updated plugin leads to a config screen”.

**Comment by ophian** [comment] 2015-02-24 12:43
Well, if you offer an "update all" button to the majority, what do you think the users will use...?

The thing is, upgrading plugins is not only a simple copy from mirror to remote file system. It sets config changes etc and has this special new feature to outbreak following the normal routine. This is/are the new upgrade hook(s). CKE for example does need `backend_plugins_update` to immediate deflate the zip and open the plugin config to work properly. It can't be done later. - I would not like to have this silently  reverted by other comfort mainstream additions.

**Comment by yellowled** [comment] 2015-02-24 12:49
The interesting question here is: what happens if multiple plugins are updated using UpdateAll and one of the updated plugins opens the plugin config screen? Is the config screen suppressed? I assume than everything that needs to be executed during a plugin update *is* updated, but what if an update requires user interaction?

**Comment by ophian** [comment] 2015-02-24 13:10
Yes, that about was/is my question. For CKE it is even more complicated, since the `backend_plugins_update` hook calls the `external_plugin` hook by header('Location: '..), to redirect to the plugin config, force deflation, do this and that and notify (and wait for) the user. It should not be suppressed. 
Simply in question, does the javascript UpdateAll respect uncertain breakage?

**Comment by onli** [comment] 2015-02-24 14:23
> I don't understand how that stops us from implementing “go back to the Update plugins page after updating a plugin unless the updated plugin leads to a config screen”.

Because that exactly is "implementing inconsistent behaviour depending on the state of the system". Very rarely that works well, normally it is highly confusing.

> Simply in question, does the javascript UpdateAll respect uncertain breakage?

I don't like the current discussion. The feature we are talking about is implemented, got tested, was in a feature branch and open for all to see. It does not change the update procedure in the sense that it only clicks on the button, in an ajax request. For what you are describing it sound like 
 
 1. why are you doing it that complicated?
 2. You seriously should test it.

For the issue at hand: I won't implement it because the concerns I voiced and because I provided a better solution to the use case.

**Comment by yellowled** [comment] 2015-02-24 14:52
> Or do you mean: Always to go to the update list even when there are no more updates, simply changing the behaviour?

Let me put it this way: it wasn't what I meant, but I would not mind that. :)

Or in Scrum terms: As a user, if I click on the “Update” button for a *single* plugin in a list of updateable plugins, I would expect to be directed back to that list of updateable plugins after the update, either to do more (single) updates or to confirm that all plugins have been updated.

If you think it is more consistent to *always* go back to the list of updateable plugins, even after using “Update All”, I'm fine with that.

> An update should not need an user interaction.

That's a completely different aspect of the discussion. I think we can all agree that ideally, yes, that's the way updates should work. Personally, I don't think that's a very realistic assumption, though. ;)

Why do some plugins even go to the config screen during an update? Is it because the update requires changes in the plugin config? Because that is what opening the plugin config could imply to users.

**Comment by ophian** [comment] 2015-02-24 15:42
> The feature we are talking about is implemented, got tested, was in a feature branch and open for all to see. It does not change the update procedure in the sense that it only clicks on the button, in an ajax request.

Yes this is what you did and, beside I thought it was good to have too, I was in hope you took care for the details. 
I had two questions reopening this issue. One for the origin request, which is more or less exactly what YL describes in the Scrum terms paragraph, and secondly about the new implemented js tool taking care for certain extended behaviours. I do not want to test every extended feature we have, each time you touch or simplify a certain behaviour, because you personally do not think it is a valid usercase.
For me your answer sounds like: I don't care for the origin request and have captured it to invent a mainstream tool. Now you just say for the second question: _"Care for youself, if that may break extended features already in use. I don't!"_ 
I have put quite some time into the upgrade to config task, and I am not amused if that is not respected.
(If you just wanted to say it still allows the same extended feature upgrade behaviour as before, regarding my second question, updating one by one, then all is good. But I did not hear this.)

**Comment by yellowled** [comment] 2015-02-24 16:35
Guys, if there are still things to discuss here, please continue it in the forums, preferably in the German forum, or discuss it in the next devTalk.

I feel as if discussing it here is toxic because there are a lot of subtle undertones being used and there's a lot of stuff being read between the lines that might or might not be there.. It does not help to do that in a non-native language, that will lead to misunderstandings.

**Comment by garvinhicking** [comment] 2015-02-24 19:40
I think this is still a proposal, so discussion should be embraced.

Everyone is in the responsibility to check the feature and look for 
issues; when I implement things, I cannot possibly civer for every 
possible edge case/scenario, that's what team development is also for, 
so get opinions and possible cases.

It is very important and good that you raise concerns about plugins 
possible performing events on backend_update event hooks. We definitely 
need to test that and check what happens. As the AJAX request only calls 
the request in the backound, including HTTP redirects, it could very 
well work. To be sure, we need to test it.

Since you took very much effort for the ckeditor routine you'd be a 
great candidate to test the updateall button for that functionality. If 
it has bugs, we could openly discuss them and see if we can either 
easily fix the issues it creates; otherwise we can try to see how to 
deploy workarounds for that, or even scrap the updateall routine if it's 
too unstable.

I do think we should be able to "workaround" that, and it might very 
well work at the point we are with right now. Otherwise, we could even 
in the update routine check whether an updated plugin enlists the 
backend_update screen, and if it does, make the AJAX request get a 
specific variable to deal with that.

So: No worries! The 2.1.x tree is in development right now, nothing is 
set in stone, this is a state where everything's up for discussion.

I believe that onli's "care for your self" was really meant to be read 
as "please check that out since you know these routines better than me 
and can better test what happens (or what does not)".

**Comment by ophian** [comment] 2015-02-25 11:01
> To be sure, we need to test it.
> Since you took very much effort for the ckeditor routine you'd be a great candidate to test the updateall button for that functionality.

Yeah, right! Normally this test would be an easy appoach for all of us and I never refused to do this in the past when I was able to. But in this special case we need a live cke plugin zip upgrade, already on the mirrors, we need some more plugins to fill the list (mirrored?) and we would need to make sure it is placed inside that list, not at the end.

Since I have no clue on how Onli live-tested this for different list cases, if he ever did, or could I, without spending some hours, I do not think I am a perfect candidate for this. He should know how his js routine would react-on/handle possible list breakouts. I can't assess this. That is why I asked! Maybe it is much easier and reproducible to write some fake test cases for the JS to check this out.

I append a short description why this happens to be and may look complicated, since it requests to the plugin config on zip case, or falls back to the backend plugins UPGRADE page. It works very well and should be kept as an extended upgrade possibility. 
> This Spartacus fetch needs a forced fallback, to execute the zip deflate, before new configs are set. 
> 
> > Use the update-plugin event hook to always make a new HTTP request (i.e. to /external_plugin/update_plugin_XXX), the plugin listens to this, and then the new http request will have loaded the new plugin code.

**Comment by garvinhicking** [comment] 2015-02-25 11:59
Hi Ian!

> Yeah, right! Normally this test would be an easy appoach for all of us
> and I never refused to do this in the past when I was able to. But in
> this special case we need a live cke plugin zip upgrade, already on the
> mirrors, we need some more plugins to fill the list (mirrored?) and we
> would need to make sure it is placed inside that list, not at the end.

But you could just backdate your locally installed plugin, change the 
local version number so that an upgrade is possible...? And replace the 
local files with an old plugin versions...?

I believe that's how onli also tested his upgrades methods...

**Comment by onli** [comment] 2015-02-25 12:21
>  I believe that's how onli also tested his upgrades methods...

Yes, I changed the version numbers of all plugins to 0.01

**Comment by garvinhicking** [comment] 2015-03-13 09:51
@onli Should we close this issue for now since the feature is implemented? If @ophian also tests this in the future, we can either open a new issue for found bugs, or reopen this one? (Closing now)

BTW - do we want to remove feature branches that got merged, for better clarity?

**Comment by ophian** [comment] 2015-03-13 09:58
I don't see my origin issue closed...

**Comment by onli** [comment] 2015-03-13 10:10
> @onli Should we close this issue for now since the feature is implemented?

I already closed this before.

> BTW - do we want to remove feature branches that got merged, for better clarity?

Yes. Github is offering that after merging a pull request, I think I did that already.

**Comment by garvinhicking** [comment] 2015-03-13 10:38
@ophian Ok no problem! I assigned the issue to you so that you can fill in your feedback.

If I misunderstood, please state what remains to be the issue.

**Comment by ophian** [comment] 2015-03-13 11:37
> Instead of going back to the Plugins page, go back to Update [Group] plugins page if there are more updates available?

Yes this, by updating plgins manually one by one. Onlis code is just another option for the ones that do not want do do this manually. That is why I said it is captured, since it does not work on my origin request.
If you now assign me to it, I will have to search for a solution on this, but I would prefere to see you all taking care of this (users like me) and not just keeping the JS ALL solution only.

**Comment by garvinhicking** [comment] 2015-03-13 13:04
Ah.

I personally think that if I update a plugin, it should go to the configuration page of that plugin, because possibly new configuration options should be checked by the user. If multiple plugins should be updated, I always suggest users to use a Shift-Click/Middle-Click on each plugin's update link. No?

**Comment by ophian** [comment] 2015-03-13 13:14
> I personally think that if I update a plugin, it should go to the configuration page of that plugin, because possibly new configuration options should be checked by the user. 

Yes. Singulary (and not always). But it does not!

> If multiple plugins should be updated, I always suggest users to use a Shift-Click/Middle-Click on each plugin's update link. No?

No. :)

**Comment by garvinhicking** [comment] 2015-03-13 13:17
I don't understand, what does "Singulary (and not always). But it does not!" mean please? You really need to be more verbose :-)

**Comment by ophian** [comment] 2015-03-13 13:28
If you update a plugin singulary it **does not** fall back to its config. (CKE Plugin in special should, since I used the upgrade-to-config hook, but this will now possibly fail also.)

If you have multiple plugins waiting to update, each update falls back to the plugin list page and you need to check in into the upgrade page again over and over. Therefore I wished to have a fallback to UPGRADE page modus, which is something differents than a JS ALL mode.

Verbosity vs issues already stated ...
_How come I have to declare already stated things over and over again, if it is easy enough to just read the thread again._ :)

**Comment by garvinhicking** [comment] 2015-03-13 13:43
Thank you. Now I understand.

It is nearly impossible to read through this thread due to its confugsing nature. So everyone has to contribute on making precise statements for this issue to be solved.

I'm not willing to discuss on such an passive-agressive level, though. Please watch your tone.

**Comment by ophian** [comment] 2015-03-13 13:59
Terribly sorry to read this. I do and did not not want to intend such a level. This is **not** my personal impetus, Garvin, if I am not challenged to do, which I did **not actually** see here! 
_I just have the feeling to need to say things more often than actually needed. But now I shut up again and try my very best the next time to be as precise as possible. :)_

**Comment by garvinhicking** [comment] 2015-03-13 14:07
That's good to read, thanks. Please also understand that often not only me but also others don't directly understand what you mean, and when we ask, we only ask because we DO want to understand and improve. :-)

I often feel there's a missing statement in between that explains the scenario, so I have to interpret (and misinterpret) things to get the whole picture. I simply often don't have the benefit of time to read through a whole thread, where things turned into many different directions.

Everyone of us needs to keep that in mind, to keep focussed to a productive solution; sometimes this needs repeating things, and compressing the topics so that there's a common ground to continue working on.

**Comment by ophian** [comment] 2015-03-15 14:04
I have to note this here, since that has been an issue for me for a few years now, that I never could figure out to be really clear. 

If you have multiple updates available and install them manually click by click, then the fallback is working as intended, when you always update the last plugin in list by hand. 
If you do this vice versa or unsorted you get redirected to the plugin list page!

**Closed** 2016-01-15 01:51 UTC
Labels: 2.0, backend, enhancements
